[[verbs]]
invocation = "edit"
key = "F2"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

[skin]
char_match = "yellow none"
default = "gray(22) gray(1)"
directory = "#101faf none bold"
exe = "rgb(17, 164, 181) none"
file = "gray(21) none"
file_error = "Red none"
flag_label = "gray(16) none"
flag_value = "#101faf none bold"
help_bold = "rgb(255, 187, 0) none bold"
help_code = "gray(21) gray(3)"
help_headers = "rgb(255, 187, 0) none"
help_italic = "Magenta rgb(30, 30, 40) italic"
help_paragraph = "gray(20) none"
input = "White none"
link = "Magenta none"
perm__ = "gray(5) None"
perm_r = "ansi(92) None"
perm_w = "ansi(192) None"
perm_x = "ansi(69) None"
pruning = "rgb(89, 73, 101) none Italic"
scrollbar_thumb = "rgb(255, 187, 0) none"
scrollbar_track = "rgb(80, 50, 0) none"
selected_line = "none gray(3)"
sparse = "ansi(214) None"
status_bold = "#101faf None bold"
status_code = "ansi(229) gray(5)"
status_ellipsis = "gray(19) gray(1)"
status_error = "Red gray(2)"
status_italic = "#101faf None"
status_job = "ansi(220) gray(5)"
status_normal = "gray(20) gray(3)"
tree = "rgb(89, 73, 101) none"